services:

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodb:/data/db
    networks:
      - noc-network

  postgres:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - noc-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mongo
      - postgres
    environment:
      MAILER_EMAIL: adan.cruickshank@ethereal.email
      MAILER_SECRET_KEY: tq5VdcXFWTBBua1cMg
      MAILER_HOST: smtp.ethereal.email
      MAILER_PORT: 587
      CHECK_SERVICE_URL: https://caoh29.dev

      # MONGO_PORT: 27018
      # MONGO_USER: chami29m
      # MONGO_PASSWORD: mysupersecuremongopassword
      # MONGO_DB_NAME: NOC

      # POSTGRES_PORT: 5433
      # POSTGRES_USER: chami29p
      # POSTGRES_PASSWORD: mysupersecurepostgrespassword
      # POSTGRES_DB_NAME: NOC

      # MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}
      # POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?schema=public
    networks:
      - noc-network

networks:
  noc-network:
    driver: bridge
