services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:3000
    environment:
      # MAILER_EMAIL: 
      # MAILER_RECIPIENT: 
      # MAILER_SECRET_KEY: 
      MAILER_SERVICE: gmail
      MAILER_HOST: smtp.gmail.com
      MAILER_PORT: 465
      CHECK_SERVICE_URL: https://asdvdafvdv.com
      CHECK_SERVICE_NAME: Caoh29 Portfolio

      # MONGO_PORT: 27018
      # MONGO_USER: chami29m
      # MONGO_PASSWORD: mysupersecuremongopassword
      # MONGO_DB_NAME: NOC

      # POSTGRES_PORT: 5433
      # POSTGRES_USER: chami29p
      # POSTGRES_PASSWORD: mysupersecurepostgrespassword
      # POSTGRES_DB_NAME: NOC

      # MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}
      # POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?schema=public
