services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:3000
    environment:
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_RECIPIENT: ${MAILER_RECIPIENT}
      MAILER_SECRET_KEY: ${MAILER_SECRET_KEY}
      MAILER_SERVICE: ${MAILER_SERVICE}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      CHECK_SERVICE_URL: ${CHECK_SERVICE_URL}
      CHECK_SERVICE_NAME: ${CHECK_SERVICE_NAME}
      
      # MONGO_DB_NAME: ${MONGO_DB_NAME}

      # POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}

      # MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}
      # POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?schema=public
